language: node_js
node_js:
	- 12.18.2
cache: npm

install: 
	- npm ci 
  - npm run build 

script:
	- npm test

deploy:
	provider: pages
	skip-cleanup: ture
	github-token: $GITHUB_TOKEN
	on:
		branch: master