language: node_js
node_js:
  - node

cache:
  directories:
    - ~/Application/node_modules

services:
  - mongodb

script: 
  - cd Application &&  npm install -g mocha && npm test

env:
  global:
    - COVERALLS_PARALLEL=true

jobs:
  include:
    - script: COVERALLS_FLAG_NAME=test-1 make test-coveralls-1
    - script: COVERALLS_FLAG_NAME=test-2 make test-coveralls-2
    
notifications:
  webhooks: https://coveralls.io/webhook

#after_script:  
#  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

#after_success:
#  - npm run coverage
#  - npm run coveralls

notifications:
  email: false