language: node_js
node_js:
  - node

cache:
  directories:
    - ~/Application/node_modules

service_name: travis-pro

services:
  - mongodb

script: 
  - cd Application &&  npm install -g mocha && npm test