language: node_js
node_js:
  - node

cache:
  directories:
    - ~/Application/node_modules

services:
  - mongodb

script: 
  - cd Application &&  npm install -g mocha && npm test

after_script:  
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

after_success:
  - npm run coverage
  - npm run coveralls

notifications:
  email: false